---

name: 'Run script on a remote system'
description: 'Run script on a remote system'
inputs:
  system:
    description: 'The system to run upon'
    required: true
  environment:
    description: 'Environment variables'
    required: true
  cmd:
    description: 'The command to run on the remote system'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Run command
    uses: ./job-runner/action.yaml
    run: "echo ssh ${{inputs.system}} ${{ inputs.cmd }}"
    shell: bash
