
name: Run Job
on:
  workflow_dispatch:
    inputs:
      system:
        type: string
        description: 'System to run upon'
        default: elmo
        required: true
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    paths:
      - '*'

env:
  MESSAGES: /var/log/messages
  TESTDIR: /opt/test/etc

jobs:
  run-command:
#    strategy:
#        matrix:
#            os: [ubuntu-latest, macos-13-large ]
#            os: [ macos-13-large ]
#            include:
#                - os: ubuntu-latest
#                  arch: amd64
#                - os: macos-13-large
#                  arch: arm64    
    runs-on: [self-hosted, macos, zero]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run script and command
      uses: actions/job-runner@v1
      with:
        system: ${{ inputs.system }}
        environment: ${{ env }}
        cmd: 'echo "One Command" && echo "Another Command" && echo "Yet Another Command"'
