
name: Run Job
on:
  workflow_dispatch:
    inputs:
      system:
        type: string
        description: 'System to run upon'
        default: elmo
        required: true
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    paths:
      - '*'

env:
  MESSAGES: /var/log/messages
  TESTDIR: /opt/test/etc

jobs:
  run-command:  
    runs-on: [self-hosted, macOS, ARM64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run script and command
      #uses: dmb-silver/learning-github-actions@v1
      uses: dmb-silver/learning-github-actions/job-runner@main
      with:
        system: ${{ inputs.system }}
        environment: ${{ env.MESSAGES }}
        cmd: 'echo "One Command" && echo "Another Command" && echo "Yet Another Command"'
