
name: Run Job
on:
  workflow_dispatch:
    inputs:
      system:
        description: 'System to run upon'
        required: true

jobs:
  run-command:
    runs-on: zero
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run script and command
      uses: ./.github/workflows
      with:
        system: ${{ inputs.system }}
        environment: ${{ env }}
        cmd: 'echo "One Command" && echo "Another Command" && echo "Yet Another Command"'
