
name: Run Job
on:
  workflow_dispatch:
    inputs:
      system:
        type: string
        description: 'System to run upon'
        default: elmo
        required: true
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    paths:
      - '*'

env:
  MESSAGES: /var/log/messages
  TESTDIR: /opt/test/etc

jobs:
  run-command:
    runs-on: zero
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run script and command
      uses: ./.github/workflows
      with:
        system: ${{ inputs.system }}
        environment: ${{ env }}
        cmd: 'echo "One Command" && echo "Another Command" && echo "Yet Another Command"'
